import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
const origin = process.env.SITE_URL || 'http://127.0.0.1:8787';
const browser = await chromium.launch({headless:true});
const page = await browser.newPage({viewport:{width:1280,height:900}});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
let serial=0, mode='normal', needsUsername=true, requestCount=0;
let user={id:'fixture-user',username:null,needsUsername:true,email:'private@example.invalid'};
let releaseLeaderboard;
await page.route('**/*',async route=>{
  const url=new URL(route.request().url());
  if (url.hostname.endsWith('.queue.test')) return route.fulfill({contentType:'text/html',body:'<h1>A prepared discovery</h1>'});
  if (url.origin!==origin) return route.abort();
  if (url.pathname==='/api/auth/me') return route.fulfill({json:{user}});
  if (url.pathname==='/api/random') return route.fulfill({json:{url:`https://page${++serial}.queue.test/`,visitToken:'fixture-receipt',source:'Tranco — random across the full list'}});
  if (url.pathname==='/api/account/username') {
    const name=route.request().postDataJSON().username;
    if (name==='Taken') return route.fulfill({status:409,json:{error:'That username is already taken. Choose another.'}});
    needsUsername=false; user={...user,username:name,needsUsername:false};
    return route.fulfill({json:{username:name}});
  }
  if (url.pathname==='/api/achievements/unlocked') return route.fulfill({json:{codes:['login_first','tld_biz'],items:[]}});
  if (url.pathname==='/api/leaderboard') {
    requestCount++;
    assert.equal(route.request().headers().cookie,undefined,'leaderboard request omits credentials');
    if (mode==='loading') await new Promise(resolve=>{releaseLeaderboard=resolve;});
    if (mode==='error') return route.fulfill({status:503,json:{error:'Temporary outage'}});
    const items=mode==='empty' ? [] : [{rank:1,username:'World_Wanderer',visits:2459},{rank:2,username:'Explorer',visits:1250},{rank:2,username:'Star_Surfer',visits:1250},{rank:4,username:'<img src=x onerror=alert(1)>',visits:2},{rank:5,username:'private@example.invalid',visits:1}];
    return route.fulfill({json:{items}});
  }
  if (url.pathname.startsWith('/api/')) return route.fulfill({json:{providers:{email:true},items:[],visits:3}});
  return route.continue();
});
try {
  await page.goto(origin);
  await expect(page.locator('#username-setup-modal')).toBeVisible();
  await expect(page.locator('#get')).toBeDisabled();
  await page.keyboard.press('Escape');
  await expect(page.locator('#username-setup-modal')).toBeVisible();
  const username=page.locator('#username-setup-form input');
  await username.fill('private@example.com');
  assert.equal(await username.evaluate(n=>n.checkValidity()),false);
  await username.fill('Taken');
  await page.getByRole('button',{name:'Save username',exact:true}).click();
  await expect(page.locator('#username-setup-status')).toContainText('already taken');
  await expect(page.locator('#username-setup-modal')).toBeVisible();
  await username.fill('Fresh_Explorer');
  await page.getByRole('button',{name:'Save username',exact:true}).click();
  await expect(page.locator('#username-setup-modal')).toBeHidden();
  await expect(page.locator('#get')).toBeEnabled();
  assert.equal(needsUsername,false);
  await expect(page.locator('#meta')).toHaveText('Username saved.');
  await page.locator('#get').click();
  await expect(page.locator('#url')).toContainText('.queue.test');
  await expect(page.locator('#meta')).toHaveText('');
  assert.equal((await page.locator('.statusbar').innerText()).trim(),'GitHub');
  await page.locator('#refresh').click();
  await expect(page.locator('#meta')).toHaveText('Refreshed landing');
  await expect(page.locator('#queue-status')).toBeHidden();
  await expect(page.locator('.statusbar')).not.toContainText('Tranco');
  assert.equal(await page.locator('#embed-note').count(),0);
  await page.getByRole('button',{name:'View',exact:true}).click();
  mode='loading';
  await page.getByRole('menuitem',{name:'Leaderboard',exact:true}).click();
  await expect(page.locator('#leaderboard-status')).toContainText('Loading');
  await expect.poll(()=>Boolean(releaseLeaderboard)).toBe(true);
  mode='normal'; releaseLeaderboard();
  await expect(page.locator('#leaderboard-rows tr')).toHaveCount(3);
  await expect(page.locator('#leaderboard-rows')).not.toContainText('private@');
  assert.equal(await page.locator('#leaderboard-rows img').count(),0);
  await page.screenshot({path:'/tmp/neverlanding-leaderboard.png'});
  await page.setViewportSize({width:375,height:812});
  await page.screenshot({path:'/tmp/neverlanding-leaderboard-mobile.png'});
  const bounds=await page.locator('.leaderboard-window').boundingBox();
  assert.ok(bounds.x>=0 && bounds.x+bounds.width<=375);
  await page.locator('#leaderboard-refresh').focus();
  await page.keyboard.press('Tab');
  await expect(page.getByRole('button',{name:'Close leaderboard',exact:true})).toBeFocused();
  mode='empty'; await page.locator('#leaderboard-refresh').click();
  await expect(page.locator('#leaderboard-status')).toContainText('No landings yet');
  mode='error'; await page.locator('#leaderboard-refresh').click();
  await expect(page.locator('#leaderboard-status')).toContainText('could not load');
  mode='normal'; await page.locator('#leaderboard-refresh').click();
  await expect(page.locator('#leaderboard-rows tr')).toHaveCount(3);
  await page.keyboard.press('Escape');
  await expect(page.locator('#leaderboard-modal')).toBeHidden();
  await expect(page.getByRole('button',{name:'View',exact:true})).toBeFocused();
  await page.setViewportSize({width:1280,height:900});
  await page.locator('#achievements-menu').click();
  await expect(page.locator('.achievement-tile.is-unlocked')).toHaveCount(2);
  const tile=page.locator('.achievement-tile.is-unlocked').first();
  await expect(tile).toHaveCSS('animation-name','achievement-glow');
  assert.notEqual(await tile.evaluate(n=>getComputedStyle(n).boxShadow),'none');
  assert.equal(await page.locator('.achievement-tile:not(.is-unlocked)').first().evaluate(n=>getComputedStyle(n).animationName),'none');
  await page.screenshot({path:'/tmp/neverlanding-achievement-glow.png'});
  await page.emulateMedia({reducedMotion:'reduce'});
  assert.equal(await tile.evaluate(n=>getComputedStyle(n).animationName),'none');
  assert.notEqual(await tile.evaluate(n=>getComputedStyle(n).boxShadow),'none');
  await page.getByRole('button',{name:'Close achievements dialog',exact:true}).click();
  await page.locator('#achievements-menu').click();
  assert.equal(await tile.evaluate(n=>getComputedStyle(n).animationName),'none','viewed awards retain a steady glow');
  assert.notEqual(await tile.evaluate(n=>getComputedStyle(n).boxShadow),'none');
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({passed:true,usernameSetup:true,leaderboardRequests:requestCount,privateFieldsHidden:true,mobile:true,keyboard:true,achievementGlow:true,footer:'action messages and GitHub, no discovery labels',errors}));
} finally {await browser.close();}
