-- Keep new non-flag hints playful; preserve flag instructions and all awards.
UPDATE achievements SET description = 'You are a .bizniss man.' WHERE code = 'tld_biz';
UPDATE achievements SET description = 'Give the web another life on .eco.' WHERE code = 'tld_eco';
UPDATE achievements SET description = 'Take the scenic route to .green.' WHERE code = 'tld_green';
UPDATE achievements SET description = 'Open the toolbox on .tools.' WHERE code = 'tld_tools';
UPDATE achievements SET description = 'Press start on .game.' WHERE code = 'tld_game';
UPDATE achievements SET description = 'Turn the key on .security.' WHERE code = 'tld_security';
UPDATE achievements SET description = 'Load a little .video nostalgia.' WHERE code = 'tld_video';
UPDATE achievements SET description = 'Crash a .events party.' WHERE code = 'tld_events';
UPDATE achievements SET description = 'Make a connection on .social.' WHERE code = 'tld_social';
UPDATE achievements SET description = 'Find the gears turning on .engineering.' WHERE code = 'tld_engineering';
UPDATE achievements SET description = 'Admire the pixels on .design.' WHERE code = 'tld_design';
UPDATE achievements SET description = 'Boot up a .tech discovery.' WHERE code = 'tld_tech';
UPDATE achievements SET description = 'Plug into .energy.' WHERE code = 'tld_energy';
UPDATE achievements SET description = 'There is a whole .world out there.' WHERE code = 'tld_world';
UPDATE achievements SET description = 'Find a happy little .app.' WHERE code = 'tld_app';
UPDATE achievements SET description = 'Turn the dial to .audio.' WHERE code = 'tld_audio';
UPDATE achievements SET description = 'Find the missing .info.' WHERE code = 'tld_info';
UPDATE achievements SET description = 'Drop into .chat.' WHERE code = 'tld_chat';
UPDATE achievements SET description = 'Make time for .watch.' WHERE code = 'tld_watch';
UPDATE achievements SET description = 'Unlock a .codes discovery.' WHERE code = 'tld_codes';
UPDATE achievements SET description = 'Land on a .site worth seeing.' WHERE code = 'tld_site';
UPDATE achievements SET description = 'Step through a .digital doorway.' WHERE code = 'tld_digital';
UPDATE achievements SET description = 'Open a fresh chapter on .news.' WHERE code = 'tld_news';
UPDATE achievements SET description = 'Paint your journey with .art.' WHERE code = 'tld_art';
UPDATE achievements SET description = 'Cast your browser into .net.' WHERE code = 'tld_net';
UPDATE achievements SET description = 'Find a .download destination; no download required.' WHERE code = 'tld_download';
UPDATE achievements SET description = 'See what makes .systems tick.' WHERE code = 'tld_systems';
UPDATE achievements SET description = 'Find your groove on .music.' WHERE code = 'tld_music';
UPDATE achievements SET description = 'Discover a .software destination.' WHERE code = 'tld_software';
UPDATE achievements SET description = 'Browse the classic .com neighborhood.' WHERE code = 'tld_com';
UPDATE achievements SET description = 'Visit the builders on .dev.' WHERE code = 'tld_dev';
UPDATE achievements SET description = 'Read a page from .blog.' WHERE code = 'tld_blog';
UPDATE achievements SET description = 'Float into .cloud.' WHERE code = 'tld_cloud';
UPDATE achievements SET description = 'It looks like you are visiting .help.' WHERE code = 'tld_help';
UPDATE achievements SET description = 'Get a little wiser on .edu.' WHERE code = 'tld_edu';
UPDATE achievements SET description = 'Find your way to .org.' WHERE code = 'tld_org';
UPDATE achievements SET description = 'Launch into .space.' WHERE code = 'tld_space';
UPDATE achievements SET description = 'Unpack a .zip website; no file download required.' WHERE code = 'tld_zip';
UPDATE achievements SET description = 'Find your people on .network.' WHERE code = 'tld_network';
UPDATE achievements SET description = 'A fresh boot into .computer.' WHERE code = 'tld_computer';
