"""Generate an additive D1 migration from the shared achievement definitions."""
import json, argparse
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument('--migration', required=True, help='New migration filename; existing migrations cannot be overwritten')
args = parser.parse_args()
target = Path('migrations') / Path(args.migration).name
if target.exists(): raise SystemExit('Choose a new migration name; applied migrations must not be rewritten.')
catalog = json.loads(Path('public/data/achievements.json').read_text())
def q(value): return "'" + value.replace("'", "''") + "'"
rows = []
for a in catalog['achievements']:
    rows.append('  (' + ', '.join(q(v) for v in ['ach_' + a['code'], a['code'], a['title'], a['description']]) + ')')
sql = '-- Generated by tools/generate-achievements.py. Preserve all existing IDs and earned records.\n'
sql += 'INSERT INTO achievements (id, code, title, description) VALUES\n' + ',\n'.join(rows)
sql += '\nON CONFLICT(code) DO UPDATE SET title = excluded.title, description = excluded.description;\n'
target.write_text(sql)
