"""Generate an additive D1 migration from the shared achievement definitions."""
import json
from pathlib import Path

catalog = json.loads(Path('public/data/achievements.json').read_text())
def q(value): return "'" + value.replace("'", "''") + "'"
rows = []
for a in catalog['achievements']:
    rows.append('  (' + ', '.join(q(v) for v in ['ach_' + a['code'], a['code'], a['title'], a['description']]) + ')')
sql = '-- Generated by tools/generate-achievements.py. Preserve all existing IDs and earned records.\n'
sql += 'INSERT INTO achievements (id, code, title, description) VALUES\n' + ',\n'.join(rows)
sql += '\nON CONFLICT(code) DO UPDATE SET title = excluded.title, description = excluded.description;\n'
Path('migrations/0009_complete_achievements.sql').write_text(sql)
